### ISSUE TITLE
Default values are not generated for "root" schemas/entities

### ISSUE THREAD

**Issue by Fresa** [corvus-dotnet/Corvus.JsonSchema#243]
Schema entities that has properties (sub-schemas) defined with the `default` annotation will include a `*.Defaults.cs` file including the default values of those properties. This does not seem to be the case when the entity it self contains a default value.

Schema example:
```
{
  "type": "string",
  "default": "foo"
}
```
This schema will not generate a type that includes the defined default value.

Corvus.Json.CodeGeneration.202012: 1.0.17

**Comment by mwadams** [comment]
This is a (design) bug.

We should be setting the default values as statics on the schema and then using them in the helpers for default property value retrieval on an object.

A fix will be non-breaking.

**Comment by Fresa** [comment]
Great stuff, you are fast! :)

Entities that are generated from schemas that describes objects does not get it's `DefaultInstance` set with the default values of it's properties, wouldn't that be nice?

Example:
```
foo:
  type: object
  properties:
    bar:
      type: string
      default: dolor sit amet
    fee:
      type: string
      default: lorem ipsus
  required:
  - bar
  - fee
```

Expectation:
```
var foo = Foo.DefaultInstance;
Console.WriteLine(foo.Bar); // "dolor sit amet"
Console.WriteLine(foo.Fee); // "lorem ipsus"
```

Currently it instantiates `Foo` with nothing.
