### ISSUE TITLE
AllOf schemas generate inconsistent models when combining schemas containing properties with the same name

### ISSUE THREAD

**Issue by Fresa** [corvus-dotnet/Corvus.JsonSchema#294]
When having an `AllOf` keyword combining two schemas and those schemas contains properties with the same name the generator seems to pick one of them instead of trying to combine them. Which one is chosen seem to be random causing generated models to switch randomly between them when generating.

Example:
```
allOf:
  - $ref: "http://foo.com/schema.yaml"
  - type: object
    properties:
      foo:
        type: number
        minimum: 5
```

Where `http://foo.com/schema.yaml` would define the same property, for example:
```
properties:
  foo:
    type: number
    minimum: 0
```

This would generate a class containing `foo` defined by a generated subclass from one of the schemas, seemingly picked randomly.
